name: Hamish Nuttall
favicon: null
layout_spectrum: 0.0386837013065815
typography_spectrum: 0.4718283300753683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8714506137184799
  lightness: 0.2777858339250088
  saturation: 0.45081057446077466
  rhythmicContrast: 0.10254613286815584
purpose: []
